### ISSUE TITLE
Impossible to extend the configuration as it's explained in the sample config.

### ISSUE THREAD

**Issue by gerardobort** [lencioni/SLIR#17]
...
class SLIRConfig extends SLIRConfigDefaults
...

All the attributes and the init method are defined as static in the SLIRConfigDefaults class.
So, there's no way to extend them from the SLIRConfig class.
More specifically SLIRConfigDefaults::init() will override all the "extended" attributes from SLIRConfig.

The way to extend static variables is using late static bindings (only PHP >5.3).
More info: http://php.net/manual/en/language.oop5.late-static-bindings.php

I think the configuration guide is misleading in this point.
Btw, the library is excellent, great job!

**Comment by ambroisemaupate** [comment]
Php 5.3 is now old. This issue is not relevant anymore.
