### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by dharris89** [lencioni/SLIR#2]
I get this error when I browse to /slir/install/

Error 500 - Internal server error

An internal server error has occured!
Please try again later.

**Comment by Jaethon** [comment]
Hi there..unfortunately, I am also having the same issue.  I can't even install the module.

[Wed Jan 21 13:26:44.716019 2015] [core:alert] [pid 10685:tid 139863265351424] [client 192.222.149.4:51642] /public_html/slir/.htaccess: Invalid command 'php_value', perhaps misspelled or defined by a module not included in the server configuration

Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.


Thanks for your code and time.
-George

**Comment by ambroisemaupate** [comment]
Did you try to comment or delete these lines in `.htaccess` file?

```
php_value auto_prepend_file none
php_value auto_append_file none
```

**Comment by Jaethon** [comment]
I didn't touch anything in .htaccess.  But I ended up using your older script which works great for what I need.  Thanks for answering so quickly!

**Comment by Jaethon** [comment]
Woops.. sorry.. using HIS older script :)
