### ISSUE TITLE
too much files in rendered and request directory

### ISSUE THREAD

**Issue by ddjikic** [lencioni/SLIR#31]
i have too much files in request and rendered directories so i edited SLIR.php and added

     function gethashdir( $folder = '' )
     {
        $id    = $this->requestURI();
        $parts = array_slice( str_split( $hash = md5( $id ), 2 ), 0, 2 );
         if ( ! is_dir( $folder . '/' . join( '/', $parts ) . '/' . $hash ) ) {
               mkdir( $folder . '/' . join( '/', $parts ) . '/' . $hash, 0755, true );
         }
          return $folder . '/' . join( '/', $parts ) . '/' . $hash;
     }

end edited
 
        private function getRequestCacheDir()
       {
           $configClass = SLIR::getConfigClass();
           return $this->gethashdir( $configClass::$pathToCacheDir . '/request' );
       }

       private function getRenderedCacheDir()
       {
              $configClass = SLIR::getConfigClass();
               return $this->gethashdir( $configClass::$pathToCacheDir . '/rendered' );
       }

now the structure is like
```
/request/
               - 0e/
                       -d21/
                            - 0ed21c454ba0b4ff50c8532c8a9603c5/
                                              -38738eb1a4ea56768e17c541f7ff96fa
               - 1b/
                       -b6/
                             -1bb681f79cf5dd0670090c91236b9f39/
                                               -24bc29f33c837edab9a425aaf4c025e8
```
instead of 
```
/request/
        -  38738eb1a4ea56768e17c541f7ff96fa
        -  24bc29f33c837edab9a425aaf4c025e8
```

**Comment by ambroisemaupate** [comment]
Could you create a pull request ? Thanks !
