### ISSUE TITLE
Nginx example file

### ISSUE THREAD

**Issue by timitimi** [lencioni/SLIR#32]
As Nginx doesn't use .htaccess files for pretty URLs it would be nice if you could add a 'howto' guide for those using Slir and Nginx ! Thanks !

**Comment by ambroisemaupate** [comment]
SLIR simply use the frontend-controller rewrite pattern like many CMS. 

```nginx
    # Use Front-end controller pattern
    location /slir/ {
        try_files $uri $uri/ /slir/index.php?$args;
    }
```

**Comment by dluksza** [comment]
How then image link wold look like? Something like: http://site.com/slir/w100/path/to/image.jpg?

**Comment by ambroisemaupate** [comment]
Yes

**Comment by dluksza** [comment]
At least it doesn't work in my case with wordpress. I've use "PB Responsive Images" WP plugin, already moved /slir/ to page root.

For links like: http://site.com/slir/w100/path/to/image.jpg I got 404, but when I add "?" after /slir/ images are loaded, but (of course) are note resized.

Any hints?

**Comment by ambroisemaupate** [comment]
Maybe Wordpress url_rewriting prevent SLIR to work. Can you add an exception to your `location /` nginx conf block.

**Comment by dluksza** [comment]
What do you mean by "adding exception"?

**Comment by dclawson** [comment]
Managed to get image rewrites working using the following:

    if (!-e $request_filename) { 
	rewrite ^(.+)$ /slir/index.php?$args last;    
    }

However this applies to all files. Trying to wrap these 3 lines in a ```location /slir/ {``` doesn't seem to work, just 404's.

Any ideas?

**Comment by ambroisemaupate** [comment]
If you are working with *Nginx* why don’t you create a dedicated virtual host for SLIR? You will be able to use @dclawson solution without bothering about other files.

For example create a sub-domain `assets.mydomain.com` which points to `/var/www/vhost/mydomain.com/slir` to use image Url like this : ` http://assets.mydomain.com/w100/path/to/image.jpg`, (an other advantage: you will be able to disable cookies on this domain for better bandwidth performances).

**Comment by ambroisemaupate** [comment]
I’ve just tried on *MAMP* with Nginx; it works (with no ending slash) : 

```
location /slir {
    try_files $uri $uri/ /slir/index.php?$args;
}
```

When I go to `http://localhost:7888/slir/w800-c1x1/slir/Test/images/joe-lencioni.jpg` 

I cloned a fresh *SLIR* repository in my `/Applications/MAMP/htdocs/slir`, then I added the *location* snippet in `/Applications/MAMP/conf/nginx/nginx.conf`. Give it a try.

**Comment by fabianmossberg** [comment]
I use this for nginx:

```
rewrite "^/slir/(.*)$" /slir/index.php?$1 break;
```
