### ISSUE TITLE
can't get SLIR to work on new machine; works fine on old...

### ISSUE THREAD

**Issue by ssuess** [lencioni/SLIR#33]
Hi, hopefully someone can help me, I am pulling my hair out with this. On my old web server, SLIR was working just fine, but on the new one it won't show any images at all. Here are some of the differences:

Server software: MAMP on old machine / Yosemite Server on new machine
Web Server: Apache2 on both
PHP version: 5.2 on old, 5.6 on new

both machines are pulling the correct file paths (and both are using http://site-address/path/to/file.jpg after the slir part, ie http://mysite/slir/w150-h150-c1xc1-q85/http://site-address/path/to/file.jpg). If I paste the url of just the file in the browser it shows fine, so there is no permissions problem loading the original file. If however I try to load the full path from the old machine (including the SLIR part) it will give me the resize preview, whereas on the the new machine loading this gives me a file not found error.

And btw, it does not work on the new server using query string method either, so pretty sure this is not a mod rewrite problem.

Any ideas? This is driving me crazy. Thanks!

**Comment by ambroisemaupate** [comment]
Did you check `allow_url_fopen` parameter in your `php.ini`?

As you are trying to load an external image (http://site-address/path/to/file.jpg), PHP can block this behaviour for obvious security matters. http://stackoverflow.com/questions/3488425/php-ini-file-get-contents-external-url

You always should use a local path with SLIR, not an absolute URL.

**Comment by ssuess** [comment]
Thanks very much for your quick response, I appreciate it.  Alas, allow_url_fopen is enabled in my php.ini file. And as for local or external, I have tried both and always get file not found when going through SLIR. Any other ideas?

**Comment by ssuess** [comment]
and btw, should the local path be relative to the SLIR folder? The website base? The filesystem?

**Comment by ambroisemaupate** [comment]
The local path should be relative to your website root. Eg: `/var/www/images/foo.jpg` image should be served at `http://mysite/slir/w150-h150-c1xc1-q85/images/foo.jpg`

**Comment by ssuess** [comment]
trying the local path failed at first but then trying with querystring worked. Pasting the url into browser using querystring returns an image whereas pasting the url into the browser using the mod_rewrite string returns a file not found error. So that leads me to believe I have a mod_rewrite problem, but it shows as enabled in phpinfo, is there something else I have to add to get it to work? Thanks again for your help.

**Comment by ssuess** [comment]
I just got mod_rewrite working and that has fixed it. Thank you so much for your help, it made a huge difference.

**Comment by ambroisemaupate** [comment]
You’re welcome.
