### ISSUE TITLE
Re-size based on min width/height

### ISSUE THREAD

**Issue by Lomacar** [lencioni/SLIR#34]
Would it be too much trouble to have an option to resize based on a minimum width and height, rather than maximum? This would emulate CSS background-size: cover, rather than contain. It would be very handy but I can't quite follow the code so I don't know how to change it myself.

**Comment by ambroisemaupate** [comment]
If you want to emulate CSS `background-size: cover`, you can use `crop` attribute combined with `width` or `height`: `/slir/c600x400-w600/path/to/image.jpg`. This will generate a 600px x 400px image whatever you original image ratio is.
