### ISSUE TITLE
Cant use relative path

### ISSUE THREAD

**Issue by iantearle** [lencioni/SLIR#46]
Cant seem to get this to use a relative path/to/image works great if I use the full url, but I dont really want the path to be a url including all the http in it.

If I dont put the absolute url in for the /path/to/image.png then I get the error message showing me the path. Which is /var/www/c1x1/uploads.... etc this would work I am assuming if the path didn't have c1x1 in it? How can I get this library  to not include the functions in the path to the image?

**Comment by dalecosp** [comment]
Are you using mod_rewrite?

**Comment by iantearle** [comment]
Hi, yes, I was, but had to change the document root - which was some mighty digging around and experimenting with.
